export const OPTIONS = [
  { key: 'A', label: 'A) 0 — High risk / Never / Yes (bad)', score: 0 },
  { key: 'B', label: 'B) 1 — Some concern / Rarely / Sometimes', score: 1 },
  { key: 'C', label: 'C) 2 — Mostly okay / Often / Usually', score: 2 },
  { key: 'D', label: 'D) 3 — Low risk / Good / Always / No', score: 3 },
]

export const QUESTIONS = [
  {
    id: 1,
    text: 'When using an online tool that can write homework or answers, how likely is the child to use it to cheat?',
    pillar: 'E',
    weight: 2,
    choices: {
      A: 'Often uses it to cheat',
      B: 'Sometimes uses it to cheat',
      C: 'Rarely uses it to cheat',
      D: 'Never uses it to cheat',
    },
  },
  {
    id: 2,
    text: 'Does the child understand that online content (images/text) can be copyrighted and shouldn’t be reused without permission?',
    pillar: 'E',
    weight: 1.5,
    choices: {
      A: 'Does not understand copyright at all',
      B: 'Limited understanding',
      C: 'Mostly understands',
      D: 'Good understanding / always asks permission',
    },
  },
  {
    id: 3,
    text: 'If an AI says something mean or false about someone, how likely is the child to believe and share it immediately?',
    pillar: 'CC',
    weight: 2,
    choices: {
      A: 'Always believes and shares',
      B: 'Often believes/shares',
      C: 'Sometimes questions before sharing',
      D: 'Never shares without checking',
    },
  },
  {
    id: 4,
    text: 'Does the child know not to share passwords, OTPs, or private info online (including with "friends")?',
    pillar: 'DH',
    weight: 2,
    choices: {
      A: 'Shares passwords regularly',
      B: 'Sometimes shares or unsure',
      C: 'Rarely shares',
      D: 'Never shares passwords / knows rules',
    },
  },
  {
    id: 5,
    text: 'How often does the child use AI chatbots unsupervised (at home/phone) for entertainment or help?',
    pillar: 'TE',
    weight: 1.5,
    choices: {
      A: 'Daily and unsupervised',
      B: 'Several times a week',
      C: 'Occasionally',
      D: 'Never or only with adult',
    },
  },
  {
    id: 6,
    text: 'When given unclear instructions (e.g., "Write this essay"), can the child evaluate whether the result is appropriate or needs correction?',
    pillar: 'CC',
    weight: 2,
    choices: {
      A: 'Cannot evaluate / accepts blindly',
      B: 'Sometimes notices problems',
      C: 'Mostly evaluates and corrects',
      D: 'Consistently evaluates and fixes issues',
    },
  },
  {
    id: 7,
    text: 'If an online service asks for a photo or location, does the child ask an adult before sharing?',
    pillar: 'SG',
    weight: 1.5,
    choices: {
      A: 'Never asks; shares freely',
      B: 'Sometimes asks',
      C: 'Usually asks',
      D: 'Always asks an adult before sharing',
    },
  },
  {
    id: 8,
    text: 'Does the child understand that AI can be wrong and sometimes invent facts ("hallucinate")?',
    pillar: 'CC',
    weight: 1.5,
    choices: {
      A: 'Thinks AI is always correct',
      B: 'Sometimes doubts AI',
      C: 'Usually questions surprising answers',
      D: 'Knows AI can be wrong and checks sources',
    },
  },
  {
    id: 9,
    text: 'How frequently does the child post personal information (full name, school, address) on public platforms?',
    pillar: 'DH',
    weight: 2,
    choices: {
      A: 'Posts personal info often',
      B: 'Occasionally posts',
      C: 'Rarely posts',
      D: 'Never posts personal details',
    },
  },
  {
    id: 10,
    text: 'Is there a family rule/time-limit about screen/AI use that the child follows?',
    pillar: 'SG',
    weight: 1.5,
    choices: {
      A: 'No rules or never follows',
      B: 'Rules exist but rarely followed',
      C: 'Usually follows family rules',
      D: 'Follows clear rules consistently',
    },
  },
  {
    id: 11,
    text: 'If a chatbot gives steps that seem risky (e.g., "hide something" or "bypass rules"), would the child follow without question?',
    pillar: 'E',
    weight: 2,
    choices: {
      A: 'Would follow risky instructions',
      B: 'Might follow sometimes',
      C: 'Unlikely to follow',
      D: 'Would refuse and ask an adult',
    },
  },
  {
    id: 12,
    text: 'Does the child know how to spot fake images or manipulated content?',
    pillar: 'CC',
    weight: 1,
    choices: {
      A: 'Cannot spot manipulated content',
      B: 'Sometimes spots obvious fakes',
      C: 'Often spots manipulated images',
      D: 'Consistently detects fakes and questions sources',
    },
  },
  {
    id: 13,
    text: 'How often does the child install apps/extensions without adult approval?',
    pillar: 'TE',
    weight: 1.5,
    choices: {
      A: 'Installs without approval frequently',
      B: 'Sometimes installs without asking',
      C: 'Rarely installs without approval',
      D: 'Never installs without parental approval',
    },
  },
  {
    id: 14,
    text: 'Would the child share a private photo of someone else without permission?',
    pillar: 'E',
    weight: 2,
    choices: {
      A: 'Would share private photos without permission',
      B: 'Might share sometimes',
      C: 'Unlikely to share',
      D: 'Would never share without consent',
    },
  },
  {
    id: 15,
    text: 'If an AI recommends a website/product, does the child check who made it or ask before using/buying?',
    pillar: 'DH',
    weight: 1,
    choices: {
      A: 'Never checks source',
      B: 'Rarely checks',
      C: 'Usually checks',
      D: 'Always checks source/asks first',
    },
  },
  {
    id: 16,
    text: 'Does the child understand basic privacy settings on platforms they use (private account, blocking)?',
    pillar: 'DH',
    weight: 1.5,
    choices: {
      A: 'Does not understand privacy settings',
      B: 'Limited understanding',
      C: 'Good understanding',
      D: 'Strong understanding and uses settings',
    },
  },
  {
    id: 17,
    text: 'How well does the child manage attention when using AI tools (does use often disrupt homework/sleep)?',
    pillar: 'TE',
    weight: 1.5,
    choices: {
      A: 'Attention is frequently disrupted',
      B: 'Often distracted',
      C: 'Mostly focused',
      D: 'Very good attention management',
    },
  },
  {
    id: 18,
    text: 'Is the child able to follow a multi-step safety rule (e.g., check source → ask parent → only use accepted tool)?',
    pillar: 'CC',
    weight: 1.5,
    choices: {
      A: 'Cannot follow multi-step safety rules',
      B: 'Struggles sometimes',
      C: 'Usually follows with reminders',
      D: 'Follows multi-step rules reliably',
    },
  },
  {
    id: 19,
    text: 'Does the child know who to tell if they see something online that scares or confuses them?',
    pillar: 'SG',
    weight: 1.5,
    choices: {
      A: 'Does not know who to tell',
      B: 'Maybe knows one person',
      C: 'Usually knows who to tell',
      D: 'Clearly knows and will report concerns',
    },
  },
  {
    id: 20,
    text: 'Does the child use AI to generate content and then pass it as their own work without disclosure?',
    pillar: 'E',
    weight: 2,
    choices: {
      A: 'Frequently passes AI work as their own',
      B: 'Sometimes does this',
      C: 'Rarely does this',
      D: 'Never passes AI work as their own / discloses',
    },
  }
]
